zuul:
  prefix: 
  routes:
    ms-user:
      path: /user/**
      sensitive-headers: 
      service-id: ms-user
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8167/eureka
    
server:
  port: 8080
  
spring:
  application:
    name: ms-zuul