zuul:
  prefix: /services
  routes:
    user:
      path: /user/**
      service-id: MS-USERSERVICE
      #url:  http://localhost:8008
    notes:
      path: /notes/**
      service-id: MS-NOTESERVICE
  host:
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 60000 

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
