zuul:
  prefix: /services
  routes:
    user:
      path: /user/**
      service-id: ms-user
    notes:
      path: /notes/**
      service-id: ms-note
  host:
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 60000 

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  cloud:
    config:
      uri: http://localhost:8081
