spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://localhost:3306/microservicedemo
        username: root
        password: bridgeit1234
        driver-class-name: com.mysql.jdbc.Driver
    
