spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create
    datasource:
        url: jdbc:mysql://localhost:3306/microservicedemo
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    
