server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BridgeLabzSource/ms-config-data.git
          username: ${GITHUB_ADMIN_USERNAME}
          password: ${GITHUB_ADMIN_PASSWORD}
  application:
    name: config-server