server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bl-sid/fundoonotes-config.git
          #uri: https://github.com/17satyendra/spring-cloudConfig.git 
  application:
    name: config-server
