server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BridgeLabzSource/ms-config-data.git
          username: admin@bridgelabz.com
          password: bridge1@bz
  application:
    name: config-server